services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    environment:
      - DOCKER_ENV=true
    ports:
      - "8000:80"
    volumes:
      - ./php/src:/var/www/html/php/src
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres_wbd
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
